// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.doando.domain.payment;

import javax.persistence.Entity;
import org.doando.domain.payment.Paypal;

privileged aspect Paypal_Roo_Jpa_Entity {
    
    declare @type: Paypal: @Entity;
    
}
